# See also: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: >-
  Unit/Smoke Tests
on:
  workflow_call: {}
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'    
      - '**.png'    
permissions:
  contents: read
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"         
      - name: Initialize
        run: make clean init      
      - name: Static-Analysis
        run: make static-analysis
      - name: Unit Tests
        run: make utest
      - name: Smoke Tests
        run: make stest